apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "windrose.fullname" . }}-saves
  labels:
    {{- include "windrose.labels" . | nindent 4 }}
  {{- with .Values.persistence.saves.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.persistence.saves.accessMode }}
  storageClassName: {{ .Values.persistence.saves.storageClass | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.saves.size }}
